### ISSUE TITLE
可以配置排除的目录吗

### ISSUE THREAD

**Issue by H-Haynes** [MellowCo/unplugin-transform-we-class#1]

**Comment by MellowCo** [comment]
目前没有

**Comment by MellowCo** [comment]
为什么要配置排除的目录呢

**Comment by 38888** [comment]
好像是有问题 @/components/ 里面的组件 报错🤒
初学前端也可能是我 没配置好。。但是@/components/ 是下载的别人写好的。不引入插件的话 @/components/ 可以正常使用 可以留个vx交流嘛

**Comment by MellowCo** [comment]
> 好像是有问题 @/components/ 里面的组件 报错🤒 初学前端也可能是我 没配置好。。但是@/components/ 是下载的别人写好的。不引入插件的话 @/components/ 可以正常使用 可以留个vx交流嘛

可能是匹配规则原因 能知道是哪个组件吗 提供相关组件代码

**Comment by H-Haynes** [comment]
tmui组件库，他的写法与规则有些冲突，所以想将其排除

**Comment by 38888** [comment]
作者留一下 vx 晚点我弄个报错demo

**Comment by 38888** [comment]
> > 好像是有问题 @/components/ 里面的组件 报错🤒 初学前端也可能是我 没配置好。。但是@/components/ 是下载的别人写好的。不引入插件的话 @/components/ 可以正常使用 可以留个vx交流嘛
> 
> 可能是匹配规则原因 能知道是哪个组件吗 提供相关组件代码

https://github.com/38888/test

**Comment by MellowCo** [comment]
是 `''` 的匹配问题
![image](https://user-images.githubusercontent.com/47939250/186893370-da7f2d03-04ab-4857-bdb7-c6a6e410236f.png)

fixed
![image](https://user-images.githubusercontent.com/47939250/186893491-18fdbb40-794f-4df9-97ae-f71f867b5169.png)

**Comment by MellowCo** [comment]
> update 0.1.16
https://github.com/MellowCo/unplugin-transform-we-class#options
```ts
export interface Options {
  /**
   * 自定义转换规则
   * @default
   * {
      '.': '-d-',
      '/': '-s-',
      ':': '-c-',
      '%': '-p-',
      '!': '-e-',
      '#': '-w-',
      '(': '-bl-',
      ')': '-br-',
      '[': '-fl-',
      ']': '-fr-',
      '$': '-r-',
    }
   */
  rules?: Record<string, string>

  /**
   * 排除转换目标
   * @default [/[\\/]node_modules[\\/]/, /[\\/]\.git[\\/]/]
   */
  exclude?: FilterPattern

  /**
   * 需要转换的目标
   * @default [/\.[jt]sx?$/, /\.vue$/,  /\.vue\?vue/]
   */
  include?: FilterPattern
}
```
